version: "3.7"

services:

  api_service:
    build:
      context: .
    container_name: api_service
    command: ["python", "-u",  "./service.py"]
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_SQS_ENDPOINT_URL=http://localstack:4566
      - BOOKING_QUEUE_URL=http://localstack:4566/000000000000/booking-queue
    volumes:
      - ./src/api_service.py:/usr/src/app/service.py

  booking_service:
    build:
      context: .
    container_name: booking_service
    command: ["python", "-u",  "./service.py"]
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_SQS_ENDPOINT_URL=http://localstack:4566
      - BOOKING_QUEUE_URL=http://localstack:4566/000000000000/booking-queue
    volumes:
      - ./src/booking_service.py:/usr/src/app/service.py

  localstack:
    image: localstack/localstack-full
    container_name: localstack
    ports:
      - 4567-4593:4567-4593
      - 8080:8080
    environment:
      - SERVICES=sqs
      - PORT_WEB_UI=8080
      - DEBUG=0
      - DATA_DIR=./tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOSTNAME=localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack-entrypoint.sh:/docker-entrypoint-initaws.d/localstack-entrypoint.sh